# 配置语言及相应版本
language: node_js
node_js: stable

# 只监听项目源代码所在分支的变动
branches:
  only:
    - source

# 缓存依赖，节省持续集成时间
cache:
  directories:
    - node_modules

before_install:
  # 安装hexo环境
  - npm install -g hexo-cli

install:
  # 安装hexo及插件
  - npm install
  - npm install hexo-deployer-git --save

after_script:
  # 设置git提交名，邮箱
  - git config user.name "viazure"
  - git config user.email "vicrease@gmail.com"
  # 替换同目录下的 _config.yml 文件中 gh_token 字符串为 travis 后台刚才配置的变量名称，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${gh_token}/g" ./_config.yml
  # 使用 hexo 自带部署命令，可以少写几行提交静态文件的命令，提交的日志还自带文件更新时间，美滋滋~
  - hexo d

script:
  # 执行清缓存，生成静态文件操作
  - hexo clean
  - hexo g
